name: Publish nugets

on:
  push:
    tags:
      - 'v*.*.*'

env:
  NUGET_FEED: https://nuget.pkg.github.com/Itenium-Forge/index.json

jobs:
  publish-nugets:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4

      - name: 🧰 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: 📦 Restore dependencies
        run: dotnet restore

      - name: 🏷️ VERSION from tag
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
          echo "VERSION=${GITHUB_REF/refs\/tags\/v/}"

      - name: 🛠️ Build
        run: dotnet build --no-restore --configuration Release /p:Version=${VERSION}

      - name: 📦 Create NuGet packages
        run: dotnet pack --no-build --configuration Release /p:Version=${VERSION} --output ./nupkgs

      - name: 📤 Publish NuGet packages
        run: |
          for package in ./nupkgs/*.nupkg; do
            echo "Publishing $package"
            dotnet nuget push "$package" --source $NUGET_FEED --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
          done
